# Generated by Django 2.0.4 on 2018-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.CharField(default='opis', max_length=512),
            preserve_default=False,
        ),
    ]
