# Generated by Django 2.1a1 on 2018-06-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobad', '0004_employer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
