# Generated by Django 2.1a1 on 2018-06-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobad', '0006_auto_20180606_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2048)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobad.Advertisement')),
            ],
        ),
    ]
