# Generated by Django 2.1a1 on 2018-06-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobad', '0007_advertisementreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyform',
            name='reply',
        ),
    ]
